#!/bin/bash
# Insider Plugin Setup Script
# Configures Claude Code search-backup hooks in the user's current project.
#
# Usage:
#   ./tools/setup.sh                           (writes hooks into $(pwd)/.claude/)
#   ./tools/setup.sh --check-only              (verify without modifying)
#   ./tools/setup.sh --project-root <dir>      (write hooks into <dir>/.claude/)
#
# Run this from the project where you want /industry and /company to operate.
# When the plugin is installed via /plugin install, run setup.sh from your
# working project, NOT from the plugin's install directory.

set -e

PROJECT_ROOT="$(pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default hooks configuration
HOOKS_CONFIG='{
  "_description": "Auto-generated by insider plugin setup. Hooks for automatic search backup.",
  "hooks": {
    "PostToolUse": [
      {
        "matcher": "WebSearch|WebFetch|mcp__gemini-search__web_search",
        "hooks": [
          {
            "type": "command",
            "command": "jq -c \x27{ts: now, tool: .tool_name, query: (.tool_input.query // .tool_input.url // empty), result_length: ((.tool_response | tostring) | length)}\x27 >> .checkpoint/search-backup.jsonl 2>/dev/null || true"
          }
        ]
      }
    ]
  }
}'

log_info() {
  echo -e "${BLUE}[INFO]${NC} $1"
}

log_ok() {
  echo -e "${GREEN}[OK]${NC} $1"
}

log_warn() {
  echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
  echo -e "${RED}[ERROR]${NC} $1"
}

check_only=false
while [ $# -gt 0 ]; do
  case "$1" in
    --check-only)
      check_only=true
      shift
      ;;
    --project-root)
      if [ -z "${2:-}" ]; then
        echo "Error: --project-root requires a directory argument" >&2
        exit 2
      fi
      PROJECT_ROOT="$2"
      shift 2
      ;;
    -h|--help)
      sed -n '2,12p' "$0"
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      echo "Usage: $0 [--check-only] [--project-root <dir>]" >&2
      exit 2
      ;;
  esac
done

SETTINGS_FILE="$PROJECT_ROOT/.claude/settings.json"
BACKUP_DIR="$PROJECT_ROOT/.checkpoint"

echo ""
echo "========================================"
echo "  Insider Plugin Setup"
echo "========================================"
echo ""
log_info "Target project: $PROJECT_ROOT"
echo ""

# Step 1: Check if .claude directory exists
if [ ! -d "$PROJECT_ROOT/.claude" ]; then
  if [ "$check_only" = true ]; then
    log_error ".claude/ directory not found"
    exit 1
  fi
  log_info "Creating .claude/ directory..."
  mkdir -p "$PROJECT_ROOT/.claude"
  log_ok ".claude/ directory created"
else
  log_ok ".claude/ directory exists"
fi

# Step 2: Check if .checkpoint directory exists
if [ ! -d "$BACKUP_DIR" ]; then
  if [ "$check_only" = true ]; then
    log_warn ".checkpoint/ directory not found (will be created on first use)"
  else
    log_info "Creating .checkpoint/ directory..."
    mkdir -p "$BACKUP_DIR"
    log_ok ".checkpoint/ directory created"
  fi
else
  log_ok ".checkpoint/ directory exists"
fi

# Step 3: Check if settings.json exists
if [ ! -f "$SETTINGS_FILE" ]; then
  if [ "$check_only" = true ]; then
    log_error "$SETTINGS_FILE not found"
    exit 1
  fi
  log_info "Creating $SETTINGS_FILE with hooks configuration..."
  echo "$HOOKS_CONFIG" > "$SETTINGS_FILE"

  # Validate JSON
  if jq empty "$SETTINGS_FILE" 2>/dev/null; then
    log_ok "$SETTINGS_FILE created and validated"
  else
    log_error "Generated JSON is invalid"
    rm "$SETTINGS_FILE"
    exit 1
  fi
else
  log_warn "$SETTINGS_FILE already exists"

  # Check if hooks already configured
  if jq -e '.hooks.PostToolUse' "$SETTINGS_FILE" >/dev/null 2>&1; then
    log_ok "Hooks already configured in $SETTINGS_FILE"

    if [ "$check_only" = true ]; then
      exit 0
    fi

    # Ask if user wants to update
    echo ""
    read -p "Hooks already exist. Update to latest configuration? [y/N] " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
      log_info "Skipping hooks update"
      exit 0
    fi
  fi

  if [ "$check_only" = true ]; then
    log_warn "Hooks not configured in existing $SETTINGS_FILE"
    exit 1
  fi

  # Merge hooks into existing settings
  log_info "Merging hooks into existing $SETTINGS_FILE..."

  # Backup original
  cp "$SETTINGS_FILE" "$SETTINGS_FILE.bak.$(date +%s)"

  # Merge: add hooks to existing JSON
  jq --argjson hooks '{"PostToolUse":[{"matcher":"WebSearch|WebFetch|mcp__gemini-search__web_search","hooks":[{"type":"command","command":"jq -c \x27{ts: now, tool: .tool_name, query: (.tool_input.query // .tool_input.url // empty), result_length: ((.tool_response | tostring) | length)}\x27 >> .checkpoint/search-backup.jsonl 2>/dev/null || true"}]}]}' '
    if .hooks then
      .hooks.PostToolUse = $hooks.PostToolUse
    else
      .hooks = $hooks
    end
  ' "$SETTINGS_FILE" > "$SETTINGS_FILE.tmp"

  mv "$SETTINGS_FILE.tmp" "$SETTINGS_FILE"

  if jq empty "$SETTINGS_FILE" 2>/dev/null; then
    log_ok "Hooks merged into $SETTINGS_FILE"
  else
    log_error "Merge failed, restoring backup..."
    cp "$SETTINGS_FILE.bak."* "$SETTINGS_FILE"
    exit 1
  fi
fi

# Step 4: Check optional dependencies
echo ""
log_info "Checking optional dependencies..."

if command -v gemini >/dev/null 2>&1; then
  log_ok "Gemini CLI found ($(gemini --version 2>/dev/null || echo 'version unknown'))"
  log_info "  mcp__gemini-search__web_search will be available as a search fallback"
else
  log_warn "Gemini CLI not found"
  echo ""
  echo "  The plugin uses mcp__gemini-search__web_search as a search fallback."
  echo "  Without Gemini CLI, research still works but resilience is reduced"
  echo "  for non-English sources and real-time queries."
  echo ""
  echo "  To install:"
  echo "    npm install -g @anthropic-ai/gemini-cli"
  echo ""
  echo "  The plugin intentionally does NOT bundle .claude/mcp.json to avoid"
  echo "  collision with any Gemini MCP server you may already have configured."
  echo "  See references/known-open-problems.md § Open problem 4 for details."
  echo ""
fi

# Step 5: Check permissions
echo ""
log_info "Checking required permissions..."

# Try to validate by doing a test write
if touch "$BACKUP_DIR/.test" 2>/dev/null; then
  rm "$BACKUP_DIR/.test"
  log_ok "Write permission to .checkpoint/ confirmed"
else
  log_error "Cannot write to .checkpoint/ directory"
  exit 1
fi

# Step 6: Summary
echo ""
echo "========================================"
echo "  Setup Complete"
echo "========================================"
echo ""
log_ok "Hooks backup configured"
echo ""
echo "What this does:"
echo "  - Every search tool call is auto-backed up to .checkpoint/search-backup.jsonl"
echo "  - If an agent crashes, raw search data can be recovered from backup"
echo ""
echo "Next steps:"
echo "  1. Restart Claude Code to load new settings (or open /hooks menu)"
echo "  2. Run: /industry <industry-name> to start research"
echo ""
